site_name: Programming Engineer
site_url: https://programming-engineer.nl

nav:
  - About: index.md
  - Blog: blog/index.md
  - Procedure: procedure.md
  - Projects: projects.md
  - Contact: contact.md

theme:
  name: material
  language: en
  favicon: img/favicon.ico
  logo: assets/logo.webp
  custom_dir: overrides


  palette:
    # Palette for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: custom
      accent: yellow

    # Palette for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: deep orange


extra_css:
  - assets/stylesheets/extra.css

plugins:
  - tags
  - blog:
      post_url_format: "{slug}"
      archive: false

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  analytics:
    provider: google
    property: G-2E0FJM8D4B